version: '3.8'

services:
  app:
    build: .
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      - CI_ENVIRONMENT=development
    dns:
    - 8.8.8.8
    - 8.8.4.4